-- ========================================================
-- SCRIPT SQL COMPLET & SÉCURISÉ POUR SUPABASE MDLE
-- Ce script est 100% ré-exécutable sans aucune erreur
-- ========================================================

-- 1. Table de la Carte / Cafétéria (menu_items)
CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    price TEXT NOT NULL,
    description TEXT,
    is_available BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Table de l'Agenda (events)
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    date TEXT NOT NULL,
    location TEXT,
    description TEXT,
    payment_link TEXT,
    price TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Table des Commandes de Roses (rose_orders)
CREATE TABLE IF NOT EXISTS public.rose_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    buyer_firstname TEXT NOT NULL,
    buyer_lastname TEXT NOT NULL,
    buyer_class TEXT NOT NULL,
    receiver_firstname TEXT NOT NULL,
    receiver_lastname TEXT NOT NULL,
    receiver_class TEXT NOT NULL,
    color TEXT NOT NULL CHECK (color IN ('Rouge', 'Rose')),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    is_anonymous BOOLEAN DEFAULT false,
    message TEXT,
    total_price NUMERIC(10,2) NOT NULL,
    is_paid BOOLEAN DEFAULT false,
    is_delivered BOOLEAN DEFAULT false
);

-- 4. Table des Projets et Opérations Dynamiques (projects)
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    emoji TEXT DEFAULT '🚀',
    badge_tag TEXT DEFAULT 'Opération MDLE',
    is_active BOOLEAN DEFAULT TRUE,
    has_reservation_form BOOLEAN DEFAULT TRUE,
    form_config JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Table des Soumissions / Réservations par Projet (project_submissions)
CREATE TABLE IF NOT EXISTS public.project_submissions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
    project_slug TEXT NOT NULL,
    buyer_firstname TEXT NOT NULL,
    buyer_lastname TEXT NOT NULL,
    buyer_class TEXT NOT NULL,
    receiver_firstname TEXT,
    receiver_lastname TEXT,
    receiver_class TEXT,
    selected_options JSONB DEFAULT '{}'::jsonb,
    quantity INTEGER DEFAULT 1,
    is_anonymous BOOLEAN DEFAULT FALSE,
    message TEXT,
    total_price NUMERIC(10, 2) DEFAULT 0.00,
    is_paid BOOLEAN DEFAULT FALSE,
    is_delivered BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index d'optimisation
CREATE INDEX IF NOT EXISTS idx_projects_slug ON public.projects(slug);
CREATE INDEX IF NOT EXISTS idx_submissions_project_id ON public.project_submissions(project_id);
CREATE INDEX IF NOT EXISTS idx_submissions_project_slug ON public.project_submissions(project_slug);

-- Active RLS sur toutes les tables
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rose_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_submissions ENABLE ROW LEVEL SECURITY;

-- Nettoyage des anciennes politiques RLS pour éviter tout conflit
DROP POLICY IF EXISTS "Lecture publique menu" ON public.menu_items;
DROP POLICY IF EXISTS "Ecriture publique menu" ON public.menu_items;
DROP POLICY IF EXISTS "Modification publique menu" ON public.menu_items;
DROP POLICY IF EXISTS "Suppression publique menu" ON public.menu_items;

DROP POLICY IF EXISTS "Lecture publique events" ON public.events;
DROP POLICY IF EXISTS "Ecriture publique events" ON public.events;
DROP POLICY IF EXISTS "Modification publique events" ON public.events;
DROP POLICY IF EXISTS "Suppression publique events" ON public.events;

DROP POLICY IF EXISTS "Accès rose_orders" ON public.rose_orders;

DROP POLICY IF EXISTS "Lecture publique des projets" ON public.projects;
DROP POLICY IF EXISTS "Écriture admin des projets" ON public.projects;
DROP POLICY IF EXISTS "Insertion publique des réservations" ON public.project_submissions;
DROP POLICY IF EXISTS "Accès complet réservations" ON public.project_submissions;

-- Création des politiques RLS propres
CREATE POLICY "Lecture publique menu" ON public.menu_items FOR SELECT USING (true);
CREATE POLICY "Ecriture publique menu" ON public.menu_items FOR ALL USING (true);

CREATE POLICY "Lecture publique events" ON public.events FOR SELECT USING (true);
CREATE POLICY "Ecriture publique events" ON public.events FOR ALL USING (true);

CREATE POLICY "Accès rose_orders" ON public.rose_orders FOR ALL USING (true);

CREATE POLICY "Lecture publique des projets" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Écriture admin des projets" ON public.projects FOR ALL USING (true);

CREATE POLICY "Insertion publique des réservations" ON public.project_submissions FOR INSERT WITH CHECK (true);
CREATE POLICY "Accès complet réservations" ON public.project_submissions FOR ALL USING (true);
