-- ========================================================
-- SCHÉMA DE RÉFÉRENCE SÉCURISÉ — SUPABASE MDLE
-- Les écritures et les données élèves transitent uniquement par les route handlers serveur.
-- ========================================================

CREATE TABLE IF NOT EXISTS public.menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  price TEXT NOT NULL,
  description TEXT,
  is_available BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  location TEXT,
  description TEXT,
  payment_link TEXT,
  price TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.rose_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  buyer_firstname TEXT NOT NULL,
  buyer_lastname TEXT NOT NULL,
  buyer_class TEXT NOT NULL,
  receiver_firstname TEXT NOT NULL,
  receiver_lastname TEXT NOT NULL,
  receiver_class TEXT NOT NULL,
  color TEXT NOT NULL CHECK (color IN ('Rouge', 'Rose')),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  is_anonymous BOOLEAN DEFAULT false,
  message TEXT,
  total_price NUMERIC(10, 2) NOT NULL,
  is_paid BOOLEAN DEFAULT false,
  is_delivered BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  emoji TEXT DEFAULT '🚀',
  badge_tag TEXT DEFAULT 'Opération MDLE',
  is_active BOOLEAN DEFAULT TRUE,
  has_reservation_form BOOLEAN DEFAULT TRUE,
  form_config JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.project_submissions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
  project_slug TEXT NOT NULL,
  buyer_firstname TEXT NOT NULL,
  buyer_lastname TEXT NOT NULL,
  buyer_class TEXT NOT NULL,
  receiver_firstname TEXT,
  receiver_lastname TEXT,
  receiver_class TEXT,
  selected_options JSONB DEFAULT '{}'::jsonb,
  quantity INTEGER DEFAULT 1 CHECK (quantity > 0),
  is_anonymous BOOLEAN DEFAULT FALSE,
  message TEXT,
  total_price NUMERIC(10, 2) DEFAULT 0.00,
  is_paid BOOLEAN DEFAULT FALSE,
  is_delivered BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.adherents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  class TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_projects_slug ON public.projects(slug);
CREATE INDEX IF NOT EXISTS idx_submissions_project_id ON public.project_submissions(project_id);
CREATE INDEX IF NOT EXISTS idx_submissions_project_slug ON public.project_submissions(project_slug);

ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rose_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.adherents ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  policy_record RECORD;
BEGIN
  FOR policy_record IN
    SELECT policyname, tablename
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename IN (
        'menu_items',
        'events',
        'projects',
        'project_submissions',
        'rose_orders',
        'adherents'
      )
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', policy_record.policyname, policy_record.tablename);
  END LOOP;
END
$$;

REVOKE INSERT, UPDATE, DELETE ON public.menu_items FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.events FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.projects FROM anon, authenticated;
REVOKE SELECT, INSERT, UPDATE, DELETE ON public.project_submissions FROM anon, authenticated;
REVOKE SELECT, INSERT, UPDATE, DELETE ON public.rose_orders FROM anon, authenticated;
REVOKE SELECT, INSERT, UPDATE, DELETE ON public.adherents FROM anon, authenticated;

GRANT SELECT ON public.menu_items, public.events, public.projects TO anon, authenticated;

CREATE POLICY "Lecture publique menu"
  ON public.menu_items
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Lecture publique events"
  ON public.events
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Lecture publique des projets actifs"
  ON public.projects
  FOR SELECT
  TO anon, authenticated
  USING (is_active = true);
