-- Sécurisation des accès publics de la MDLE.
-- Les écritures et les données personnelles passent exclusivement par des routes
-- serveur utilisant SUPABASE_SERVICE_ROLE_KEY, jamais depuis le navigateur.

CREATE TABLE IF NOT EXISTS public.adherents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  class TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rose_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.adherents ENABLE ROW LEVEL SECURITY;

-- Supprime toute politique existante sur les tables concernées afin d’éviter
-- qu’une ancienne règle permissive reste active.
DO $$
DECLARE
  policy_record RECORD;
BEGIN
  FOR policy_record IN
    SELECT policyname, tablename
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename IN (
        'menu_items',
        'events',
        'projects',
        'project_submissions',
        'rose_orders',
        'adherents'
      )
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', policy_record.policyname, policy_record.tablename);
  END LOOP;
END
$$;

-- Révoque les mutations directes depuis le navigateur.
REVOKE INSERT, UPDATE, DELETE ON public.menu_items FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.events FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.projects FROM anon, authenticated;
REVOKE SELECT, INSERT, UPDATE, DELETE ON public.project_submissions FROM anon, authenticated;
REVOKE SELECT, INSERT, UPDATE, DELETE ON public.rose_orders FROM anon, authenticated;
REVOKE SELECT, INSERT, UPDATE, DELETE ON public.adherents FROM anon, authenticated;

-- Le site public ne lit que les contenus destinés aux visiteurs.
GRANT SELECT ON public.menu_items, public.events, public.projects TO anon, authenticated;

CREATE POLICY "Lecture publique menu"
  ON public.menu_items
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Lecture publique events"
  ON public.events
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Lecture publique des projets actifs"
  ON public.projects
  FOR SELECT
  TO anon, authenticated
  USING (is_active = true);
